added MANIFEST. Tests now skip if engine is missing!

diff --git a/src/tests/run-meta-engine b/src/tests/run-meta-engine
--- a/src/tests/run-meta-engine
+++ b/src/tests/run-meta-engine
@@ -1,12 +1,15 @@
 #!/bin/bash
 
-
-$1/meta &>log
+if [ -f ../build/$1/meta ]; then
+../build/$1/meta &>log
+else
+exit 2  # skip this test!
+fi
 
 ENDS="`grep '(META) END' log`"
 
 if [ "x$ENDS" == "x" ]; then
-exit 1
+exit 1 # failed!
 fi
 
-exit 0
+exit 0 # ok!
diff --git a/src/tests/run-test b/src/tests/run-test
--- a/src/tests/run-test
+++ b/src/tests/run-test
@@ -5,17 +5,25 @@ let DOTS=20-$LEN
 for i in `seq 1 $DOTS`; do SPAC=".$SPAC"; done
 echo -n $SPAC
 
-if [ -f $1/run.sh ]; then
+if [ -f $1/run ]; then
     cd $1
-    ./run.sh
-    if [ $? == 0 ]; then
+    echo "#!/bin/bash" >run_m4.sh
+    m4 ../tests.m4 ./run >>run_m4.sh
+    ./run_m4.sh
+    ERR=$?
+    if [ $ERR == 2 ]; then
+	echo " [SKIP]"
+	echo "$1 $SPAC [SKIP]" >>../TESTED
+	exit 0
+    fi	
+    if [ $ERR == 0 ]; then
 	echo " [OK]"
-	echo "$1 $SPAC [OK]" >>../TESTED.LOG
+	echo "$1 $SPAC [OK]" >>../TESTED
     else
 	echo " [FAILED]"
-	echo "$1 $SPAC [FAILED]" >>../TESTED.LOG
+	echo "$1 $SPAC [FAILED]" >>../TESTED
     fi	
 else
-echo " [SKIPPED]"
-echo "$1 $SPAC [SKIPPED]" >>../TESTED.LOG
+    echo " [SKIP]"
+    echo "$1 $SPAC [SKIP]" >>../TESTED
 fi
